<?php

/**
 * @file
 * Paragraphs Role Visibility module hooks.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_help().
 */
function paragraphs_role_visibility_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.paragraphs_role_visibility') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The Paragraphs Role Visibility module allow to make a single paragraph item visible for selected roles.') . '</p>';

    return $output;
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function paragraphs_role_visibility_paragraph_access(ParagraphInterface $entity, $operation, AccountInterface $account) {
  $access = AccessResult::neutral();

  if ($operation === 'view') {
    // Restrict access to view paragraph for selected through behavior users.
    $allowed_roles = $entity->getBehaviorSetting('paragraphs_role_visibility', [
      'wrapper',
      'roles',
    ]);

    if ($allowed_roles) {
      $user_roles = $account->getRoles();
      $operand = $entity->getBehaviorSetting('paragraphs_role_visibility', [
        'wrapper',
        'operand',
      ]);

      if ($operand === 'or') {
        $result = array_intersect($allowed_roles, $user_roles);
        if (empty($result)) {
          // The user does not have any of needed roles.
          $access = AccessResult::forbidden();
        }
      }
      elseif ($operand === 'and') {
        $result = array_diff($allowed_roles, $user_roles);
        if (!empty($result)) {
          // The user does not have all of needed roles.
          $access = AccessResult::forbidden();
        }
      }
    }
  }

  return $access;
}
